# Online Retail Data Analysis

## Objective

This project analyzes transactional data from an online retail business
to identify sales trends, customer behavior, product performance, and
other patterns that may support business decision-making.

## Dataset

The dataset contains transactional records from an online retail business.
The analysis focuses on sales activity, products, customers, and geographic
patterns.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
pd.set_option("display.max_columns",None)

In [3]:
f = "../data/online_retail_II.xlsx"
df = pd.read_excel(f)
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [4]:
df.shape

(525461, 8)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[us]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 38.8+ MB

In [6]:
df.describe(include="all")

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
count,525461.0,525461,522533,525461.000000,525461,525461.000000,417534.000000,525461
unique,28816.0,4632,4681,NaN,NaN,NaN,NaN,40
top,537434.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,United Kingdom
freq,675.0,3516,3549,NaN,NaN,NaN,NaN,485852
mean,NaN,NaN,NaN,10.337667,2010-06-28 11:37:36.845018,4.688834,15360.645478,NaN
min,NaN,NaN,NaN,-9600.000000,2009-12-01 07:45:00,-53594.360000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,2010-03-21 12:20:00,1.250000,13983.000000,NaN
50%,NaN,NaN,NaN,3.000000,2010-07-06 09:51:00,2.100000,15311.000000,NaN
75%,NaN,NaN,NaN,10.000000,2010-10-15 12:45:00,4.210000,16799.000000,NaN
max,NaN,NaN,NaN,19152.000000,2010-12-09 20:01:00,25111.090000,18287.000000,NaN
std,NaN,NaN,NaN,107.424110,NaN,146.126914,1680.811316,NaN

In [7]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [8]:
df[df.duplicated(keep=False)].head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
656,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom

In [9]:
#Find the number of duplicated columns
np.sum(df.duplicated())

np.int64(6865)

In [10]:
#Percentage of duplicated columns
df.duplicated().sum() / len(df) * 100

np.float64(1.306471840916833)

In [11]:
#Number of each duplicated row
df.value_counts()[df.value_counts() > 1]

Invoice  StockCode  Description                          Quantity  InvoiceDate          Price  Customer ID  Country
496431   84826      ASSTD DESIGN 3D PAPER STICKERS       1         2010-02-01 12:30:00  0.85   16415.0      United Kingdom    6
502660   17021      NAMASTE SWAGAT INCENSE               6         2010-03-25 17:18:00  0.30   13187.0      United Kingdom    6
525065   20894      HANGING BAUBLE T-LIGHT HOLDER LARGE  1         2010-10-03 14:28:00  2.95   16799.0      United Kingdom    6
534219   35953      FOLKART STAR CHRISTMAS DECORATIONS   1         2010-11-21 16:13:00  1.25   13230.0      United Kingdom    6
492784   22114      HOT WATER BOTTLE TEA AND SYMPATHY    1         2009-12-18 17:24:00  3.95   17841.0      United Kingdom    5
                                                                                                                             ..
538035   20728      LUNCH BAG CARS BLUE                  3         2010-12-09 13:03:00  1.65   16065.0      United Kingdom    2
538051   22659      LUNCH BOX I LOVE LONDON              2         2010-12-09 13:24:00  1.95   18041.0      United Kingdom    2
538155   21907      I'M ON HOLIDAY METAL SIGN            1         2010-12-09 16:52:00  2.10   16907.0      United Kingdom    2
538166   21915      RED  HARMONICA IN BOX                5         2010-12-09 18:09:00  1.25   17965.0      United Kingdom    2
538168   22739      RIBBON REEL CHRISTMAS SOCK BAUBLE    5         2010-12-09 19:23:00  1.65   14702.0      United Kingdom    2
Name: count, Length: 6331, dtype: int64

In [12]:
df[(df['Invoice'] == 496431 ) & (df['StockCode'] == 84826)]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
77256,496431,84826,ASSTD DESIGN 3D PAPER STICKERS,1,2010-02-01 12:30:00,0.85,16415.0,United Kingdom
77257,496431,84826,ASSTD DESIGN 3D PAPER STICKERS,1,2010-02-01 12:30:00,0.85,16415.0,United Kingdom
77258,496431,84826,ASSTD DESIGN 3D PAPER STICKERS,1,2010-02-01 12:30:00,0.85,16415.0,United Kingdom
77259,496431,84826,ASSTD DESIGN 3D PAPER STICKERS,1,2010-02-01 12:30:00,0.85,16415.0,United Kingdom
77260,496431,84826,ASSTD DESIGN 3D PAPER STICKERS,1,2010-02-01 12:30:00,0.85,16415.0,United Kingdom
77261,496431,84826,ASSTD DESIGN 3D PAPER STICKERS,1,2010-02-01 12:30:00,0.85,16415.0,United Kingdom

In [13]:
conteo = df.groupby(['Invoice', 'StockCode','Quantity']).size()

conteo[conteo > 1]

Invoice  StockCode  Quantity
489517   21491       1          2
         21821       1          2
         21912       1          3
         21913       1          2
         22130       6          2
                               ..
C529606  22728      -12         2
C534698  22119      -1          2
C535663  D          -1          6
C536210  22838      -1          2
C537581  S          -1          2
Length: 6507, dtype: int64

In [14]:
#To see if the duplicated rows and the registers with the same codes and quantities are the same
duplicados = df[df.duplicated(keep=False)]
duplicados.groupby(['Invoice', 'StockCode', 'Quantity']).size()

Invoice  StockCode  Quantity
489517   21491       1          2
         21821       1          2
         21912       1          3
         21913       1          2
         22130       6          2
                               ..
C525550  22158      -8          3
C528451  22179      -1          2
C529606  22728      -12         2
C534698  22119      -1          2
C536210  22838      -1          2
Length: 6418, dtype: int64

In [15]:
# Repeated combinations with Invoice, StockCode y Quantity
conteo = df.groupby(['Invoice', 'StockCode', 'Quantity']).size()

# Repited combinations that aren't exact duplicates
grupos_no_exactos = conteo[conteo > 1].drop(
    index=duplicados.groupby(['Invoice', 'StockCode', 'Quantity']).size().index,
    errors='ignore'
)

grupos_no_exactos

Invoice  StockCode  Quantity
489856   22111       5          2
490300   M           1          2
490741   22111       7          2
490963   20682       1          2
         21278       1          2
                               ..
C516614  S          -1          5
C524941  M          -1          2
C528093  S          -1          7
C535663  D          -1          6
C537581  S          -1          2
Length: 89, dtype: int64

In [16]:
df.set_index(['Invoice', 'StockCode', 'Quantity']).loc[grupos_no_exactos.index]

                                             Description         InvoiceDate  \
Invoice StockCode Quantity
489856  22111      5        SCOTTIE DOG HOT WATER BOTTLE 2009-12-02 14:36:00
                   5        SCOTTIE DOG HOT WATER BOTTLE 2009-12-02 14:36:00
490300  M          1                              Manual 2009-12-04 14:19:00
                   1                              Manual 2009-12-04 14:19:00
490741  22111      7        SCOTTIE DOG HOT WATER BOTTLE 2009-12-07 17:56:00
...                                                  ...                 ...
C535663 D         -1                            Discount 2010-11-28 11:41:00
                  -1                            Discount 2010-11-28 11:41:00
                  -1                            Discount 2010-11-28 11:41:00
C537581 S         -1                             SAMPLES 2010-12-07 12:03:00
                  -1                             SAMPLES 2010-12-07 12:03:00

                            Price  Customer ID         Country
Invoice StockCode Quantity
489856  22111      5         8.65          NaN  United Kingdom
                   5        11.26          NaN  United Kingdom
490300  M          1         0.85      12970.0  United Kingdom
                   1         0.21      12970.0  United Kingdom
490741  22111      7         8.65          NaN  United Kingdom
...                           ...          ...             ...
C535663 D         -1         1.00      14527.0  United Kingdom
                  -1         7.84      14527.0  United Kingdom
                  -1         5.67      14527.0  United Kingdom
C537581 S         -1        12.95          NaN  United Kingdom
                  -1        52.00          NaN  United Kingdom

[198 rows x 5 columns]

6825 rows were identified as exact duplicates, equivalent to 1.31% of the dataset. Some lines of the same Invoice (check) have exactly the same value in every column. It'll be conserved only one register and the copies will be droped.

In [17]:
df = df.drop_duplicates()

In [18]:
df.shape

(518596, 8)

In [19]:
df[df["Quantity"] < 0].count()

Invoice        12302
StockCode      12302
Description    10475
Quantity       12302
InvoiceDate    12302
Price          12302
Customer ID     9816
Country        12302
dtype: int64

In [20]:
df[df["Quantity"] < 0].shape[0]/len(df)*100

2.3721741008415025

In [21]:
#Number of canceled rows
df_con_c = df[df['Invoice'].str.lower().str.startswith('c', na=False)]
df_con_c.count()

Invoice        10182
StockCode      10182
Description    10182
Quantity       10182
InvoiceDate    10182
Price          10182
Customer ID     9816
Country        10182
dtype: int64

I already know that all the canceled purchases have a negative Quantity. Now I want to know were the other negative quantities come from.

In [22]:
df_neg_no_c = df[
    (df['Quantity'] < 0) &
    (~df['Invoice'].str.lower().str.startswith('c', na=False))
]

df_neg_no_c.head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3162,489660,35956,lost,-1043,2009-12-01 17:43:00,0.0,NaN,United Kingdom
3168,489663,35605A,damages,-117,2009-12-01 18:02:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
4538,489820,21133,invcd as 84879?,-720,2009-12-02 13:23:00,0.0,NaN,United Kingdom
4566,489821,85049G,NaN,-240,2009-12-02 13:25:00,0.0,NaN,United Kingdom
6556,489899,79323GR,sold as gold,-954,2009-12-03 09:41:00,0.0,NaN,United Kingdom
6576,489901,21098,NaN,-200,2009-12-03 09:47:00,0.0,NaN,United Kingdom
6911,490007,84347,21494,-720,2009-12-03 12:09:00,0.0,NaN,United Kingdom
7205,490016,21982,NaN,-1012,2009-12-03 12:30:00,0.0,NaN,United Kingdom
7559,490055,20620,NaN,-25,2009-12-03 13:22:00,0.0,NaN,United Kingdom
8553,490084,85064,NaN,-89,2009-12-03 15:37:00,0.0,NaN,United Kingdom
9308,490130,21493,lost?,-600,2009-12-03 18:28:00,0.0,NaN,United Kingdom
9667,490146,21558,NaN,-169,2009-12-04 09:29:00,0.0,NaN,United Kingdom
10508,490165,21493,NaN,-106,2009-12-04 11:32:00,0.0,NaN,United Kingdom
11973,490354,21489,NaN,-23,2009-12-04 16:39:00,0.0,NaN,United Kingdom

In [23]:
df_neg_no_c['Invoice'].value_counts().head(20)

Invoice
489464    1
489463    1
489467    1
489521    1
489655    1
489660    1
489663    1
489806    1
489820    1
489821    1
489899    1
489901    1
490007    1
490016    1
490055    1
490084    1
490130    1
490146    1
490165    1
490354    1
Name: count, dtype: int64

In [24]:
df_neg_no_c['Price'].value_counts()

Price
0.0    2121
Name: count, dtype: int64

In [25]:
df_neg_no_c['Description'].value_counts().head(20)

Description
?                         42
damages                   39
damaged                   36
missing                   24
dotcom                     6
given away                 6
smashed                    5
checked                    5
MIA                        4
Damages                    4
ebay sales                 4
crushed                    4
No Stock                   3
Damaged                    3
counted                    3
check                      3
discoloured                2
damages?                   2
Dotcom                     2
damages, lost bits etc     2
Name: count, dtype: int64

In [26]:
df = df.drop(df_neg_no_c.index)

In [27]:
df.shape

(516475, 8)

In [28]:
df[df['Quantity'] < 0].shape[0]

10181

Records of inventory adjustments identified by negative quantites, price equal to zero, and descriptions associated with losses, damage, and others were excluded, as the analysis focuses on business transactions and not internal inventory movements

In [29]:
df[df["Price"] <= 0].count()

Invoice        1563
StockCode      1563
Description     462
Quantity       1563
InvoiceDate    1563
Price          1563
Customer ID      31
Country        1563
dtype: int64

In [30]:
df[df["Price"] == 0].shape[0]

1560

In [31]:
df[df["Price"] < 0].shape[0]

3

In [32]:
df[df["Price"] == 0][["Invoice", "StockCode", "Description", "Quantity", "Price"]].head(20)

      Invoice StockCode                     Description  Quantity  Price
3161   489659     21350                             NaN       230    0.0
3731   489781     84292                             NaN        17    0.0
4674   489825     22076              6 RIBBONS EMPIRE          12    0.0
5904   489861       DOT                  DOTCOM POSTAGE         1    0.0
6378   489882    35751C                             NaN        12    0.0
6555   489898    79323G                             NaN       954    0.0
6581   489903     21166                             NaN        48    0.0
6781   489998     48185             DOOR MAT FAIRY CAKE         2    0.0
7204   490015     21982                             NaN       467    0.0
9249   490123    84508B                             NaN       184    0.0
10236  490150     84347                             NaN        80    0.0
14503  490543     37446                             NaN       222    0.0
15489  490688     21133                             NaN       270    0.0
15952  490716     22158                             NaN         6    0.0
16107  490727         M                          Manual         1    0.0
17384  490758     72008                             NaN      3000    0.0
18738  490961     22065  CHRISTMAS PUDDING TRINKET POT          1    0.0
18739  490961     22142    CHRISTMAS CRAFT WHITE FAIRY         12    0.0
20846  491053    85185F                             NaN        50    0.0
21647  491106     84922                             NaN        90    0.0

In [33]:
df[df["Price"] < 0][["Invoice", "StockCode", "Description", "Quantity", "Price"]]

        Invoice StockCode      Description  Quantity     Price
179403  A506401         B  Adjust bad debt         1 -53594.36
276274  A516228         B  Adjust bad debt         1 -44031.79
403472  A528059         B  Adjust bad debt         1 -38925.87

In [34]:
df[df["Price"] == 0]["Quantity"].value_counts().head()

Quantity
1    478
2    167
3     96
4     54
5     51
Name: count, dtype: int64

In [35]:
df[df["Price"] == 0]["Invoice"].astype(str).str.startswith("C").value_counts()

Invoice
False    1560
Name: count, dtype: int64

In [36]:
df[df["Price"] == 0]["Description"].value_counts().head(20)

Description
OWL DOORSTOP                           8
POLYESTER FILLER PAD 45x45cm           7
PICNIC BASKET WICKER LARGE             7
FLAG OF ST GEORGE CAR FLAG             6
POLYESTER FILLER PAD 40x40cm           5
SMALL POPCORN HOLDER                   5
WATERING CAN BLUE ELEPHANT             5
HEART OF WICKER SMALL                  5
ENAMEL FIRE BUCKET CREAM               5
ENAMEL WASH BOWL CREAM                 5
AIRLINE BAG VINTAGE WORLD CHAMPION     5
PICNIC BASKET WICKER SMALL             5
IVORY KITCHEN SCALES                   5
DOOR MAT UNION JACK GUNS AND ROSES     4
temp                                   4
MILK PAN PINK RETROSPOT                4
RED RETROSPOT STORAGE JAR              4
HANGING METAL STAR LANTERN             4
AIRLINE BAG VINTAGE TOKYO 78           4
WATERING CAN PINK BUNNY                4
Name: count, dtype: int64

In [37]:
df[df["Price"] < 0].shape

(3, 8)

In [38]:
df = df[df["Price"] >= 0]

In [39]:
df.shape

(516472, 8)

The 3 rows with price < 0 were dropped because they correspond to bad debts. The rest of the rows with Price = 0 were conserved due to there is not enough evidence to clasify them as mistakes.

In [40]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [41]:
print(f"La primer fecha es:",df["InvoiceDate"].min())
print(f"La ultima fecha es:",df["InvoiceDate"].max())

La primer fecha es: 2009-12-01 07:45:00
La ultima fecha es: 2010-12-09 20:01:00

In [42]:
df["Country"].value_counts()

Country
United Kingdom          476923
EIRE                      9660
Germany                   8120
France                    5754
Netherlands               2768
Spain                     1271
Switzerland               1187
Portugal                  1098
Belgium                   1053
Channel Islands            906
Sweden                     901
Italy                      729
Australia                  654
Cyprus                     546
Austria                    537
Greece                     517
United Arab Emirates       432
Denmark                    428
Norway                     369
Finland                    354
Unspecified                310
USA                        244
Japan                      224
Poland                     194
Malta                      172
Lithuania                  154
Singapore                  117
RSA                        111
Bahrain                    107
Canada                      77
Hong Kong                   76
Thailand                    76
Israel                      74
Iceland                     71
Korea                       63
Brazil                      62
West Indies                 54
Bermuda                     34
Nigeria                     32
Lebanon                     13
Name: count, dtype: int64

In [43]:
df["Country"].nunique()

40

In [44]:
df["Country"].value_counts().head(10)

Country
United Kingdom     476923
EIRE                 9660
Germany              8120
France               5754
Netherlands          2768
Spain                1271
Switzerland          1187
Portugal             1098
Belgium              1053
Channel Islands       906
Name: count, dtype: int64

Although the Dataset is international it focuses on United Kingdom

In [45]:
df.to_csv("../data/online_retail_clean.csv", index=False)